#CREATE TABLE HELLO(ID INT VARCHAR(10), DESCRIPTION VARCHAR(100))
#SELECT cast(12345 AS BINARY(5))

#SELECT cast(12345 AS VARBINARY(10))

#SELECT cast('ABC' AS CHAR(10))
#ABC IS OUTPUT

#SELECT cast('ABCDEFGHIJKLMNOPQ' AS CHAR(10)) 
#ABCDEFGHIJ IS OUTPUT

